-- Add migration script here
CREATE TABLE files (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    object_key VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    is_carrier BOOLEAN NOT NULL DEFAULT FALSE,
    is_steg_object BOOLEAN NOT NULL DEFAULT FALSE,
);
