services:

  steganography_service:
    build:
      context: ..
      dockerfile: steganography_service/Dockerfile
    container_name: steganography_service
    environment:
      EUREKA_URL: http://eureka_service:3005
      RUST_LOG: info
      PORT: 3003
    ports:
      - "3003:3003"
    depends_on:
      eureka_service:
        condition: service_healthy
    networks:
      - steganography_network

# volumes:

networks:
  steganography_network:
    name: microservices_network
    external: true
