services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "3000:3000"
    networks:
      - gateway_network

networks:
  gateway_network:
    driver: bridge
    name: microservices_network
    external: true
