services:
  eureka_service:
    build:
      context: ..
      dockerfile: eureka_service/Dockerfile
    container_name: eureka_service
    environment:
      RUST_LOG: info
      PORT: 3005
    ports:
      - "3005:3005"
    depends_on:
      eureka_postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3005/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - eureka_network

volumes:
  eureka_postgres_data:

networks:
  eureka_network:
    name: microservices_network
    external: true
